version: '3.1'
services:
  config:
    image: ecom-config-server:latest
    restart: always
    container_name: ecom-config-server
    hostname: ${CONFIG_HOSTNAME}
    environment:
      - server.port=${CONFIG_PORT}
      - spring.profiles.active=${CONFIG_SPRING_PROFILES}
    expose:
      - ${CONFIG_PORT}
    ports:
      - ${CONFIG_PORT}:${CONFIG_PORT}
    networks:
      - ecom-network
  discovery:
    image: ecom-discovery-server:latest
    restart: always
    container_name: ecom-discovery-server
    hostname: ${DISCOVERY_HOSTNAME}
    depends_on:
      - config
    environment:
      - server.port=${DISCOVERY_PORT}
      - spring.profiles.active=${DISCOVERY_SPRING_PROFILES}
      - CONFIG_SERVER_ADDRESS=${CONFIG_HOSTNAME}
      - CONFIG_SERVER_PORT=${CONFIG_PORT}
    expose:
      - ${DISCOVERY_PORT}
    ports:
      - ${DISCOVERY_PORT}:${DISCOVERY_PORT}
    networks:
      - ecom-network
  user:
    image: ecom-user-server:latest
    restart: always
    container_name: ecom-user-server
    hostname: ${USER_HOSTNAME}
    depends_on:
      - config
      - mongo
    environment:
      - server.port=${USER_PORT}
      - spring.profiles.active=${USER_SPRING_PROFILES}
      - CONFIG_SERVER_ADDRESS=${CONFIG_HOSTNAME}
      - CONFIG_SERVER_PORT=${CONFIG_PORT}
      - DISCOVERY_SERVER_ADDRESS=${DISCOVERY_HOSTNAME}
      - DISCOVERY_SERVER_PORT=${DISCOVERY_PORT}
    expose:
      - ${USER_PORT}
    ports:
      - ${USER_PORT}:${USER_PORT}
    networks:
      - ecom-network
  mongo:
    image: mongo:latest
    restart: always
    container_name: ecom-mongo-database
    hostname: ${MONGO_HOSTNAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./volumes/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - ecom-network
networks:
  ecom-network:
    driver: bridge