version: '3.1'
services:
  config:
    image: ecom-config-server:latest
    restart: always
    container_name: ecom-config-server
    hostname: ${CONFIG_HOSTNAME}
    environment:
      - server.port=${CONFIG_PORT}
      - spring.profiles.active=${CONFIG_SPRING_PROFILES}
    expose:
      - ${CONFIG_PORT}
    ports:
      - ${CONFIG_PORT}:${CONFIG_PORT}
    networks:
      - ecom-network
  discovery:
    image: ecom-discovery-server:latest
    restart: always
    container_name: ecom-discovery-server
    hostname: ${DISCOVERY_HOSTNAME}
    depends_on:
      - config
    environment:
      - server.port=${DISCOVERY_PORT}
      - spring.profiles.active=${DISCOVERY_SPRING_PROFILES}
      - CONFIG_SERVER_ADDRESS=${CONFIG_HOSTNAME}
      - CONFIG_SERVER_PORT=${CONFIG_PORT}
    expose:
      - ${DISCOVERY_PORT}
    ports:
      - ${DISCOVERY_PORT}:${DISCOVERY_PORT}
    networks:
      - ecom-network
  user:
    image: ecom-user-server:latest
    restart: always
    container_name: ecom-user-server
    hostname: ${USER_HOSTNAME}
    depends_on:
      - config
      - mongo
    environment:
      - server.port=${USER_PORT}
      - spring.profiles.active=${USER_SPRING_PROFILES}
      - CONFIG_SERVER_ADDRESS=${CONFIG_HOSTNAME}
      - CONFIG_SERVER_PORT=${CONFIG_PORT}
      - DISCOVERY_SERVER_ADDRESS=${DISCOVERY_HOSTNAME}
      - DISCOVERY_SERVER_PORT=${DISCOVERY_PORT}
    expose:
      - ${USER_PORT}
    ports:
      - ${USER_PORT}:${USER_PORT}
    networks:
      - ecom-network
  gateway:
    image: ecom-gateway-server:latest
    restart: always
    container_name: ecom-gateway-server
    hostname: ${GATEWAY_HOSTNAME}
    depends_on:
      - config
      - mongo
    environment:
      - server.port=${GATEWAY_PORT}
      - spring.profiles.active=${GATEWAY_SPRING_PROFILES}
      - CONFIG_SERVER_ADDRESS=${CONFIG_HOSTNAME}
      - CONFIG_SERVER_PORT=${CONFIG_PORT}
      - DISCOVERY_SERVER_ADDRESS=${DISCOVERY_HOSTNAME}
      - DISCOVERY_SERVER_PORT=${DISCOVERY_PORT}
    expose:
      - ${GATEWAY_PORT}
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    networks:
      - ecom-network
  mongo:
    image: mongo:latest
    restart: always
    container_name: ecom-mongo-database
    hostname: ${MONGO_HOSTNAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./volumes/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - ecom-network
  mysql:
    image: mysql:5.7
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - ecom-network
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
    networks:
      - ecom-network
    ports:
      - 8080:8080
    depends_on:
      - mysql
networks:
  ecom-network:
    driver: bridge