version: "3.1"
services:
  config:
    image: ecom-config-server:latest
    restart: always
    container_name: ecom-config-server
    hostname: ${CONFIG_HOSTNAME}
    environment:
      server.port: ${CONFIG_PORT}
      spring.profiles.active: ${CONFIG_SPRING_PROFILES}
    expose:
      - ${CONFIG_PORT}
    ports:
      - ${CONFIG_PORT}:${CONFIG_PORT}
    networks:
      - ecom-network
  discovery:
    image: ecom-discovery-server:latest
    restart: always
    container_name: ecom-discovery-server
    hostname: ${DISCOVERY_HOSTNAME}
    depends_on:
      - config
    environment:
      server.port: ${DISCOVERY_PORT}
      spring.profiles.active: ${DISCOVERY_SPRING_PROFILES}
      config.server.address: ${CONFIG_HOSTNAME}
      config.server.port: ${CONFIG_PORT}
    expose:
      - ${DISCOVERY_PORT}
    ports:
      - ${DISCOVERY_PORT}:${DISCOVERY_PORT}
    networks:
      - ecom-network
networks:
  ecom-network:
    driver: bridge