version: '3.9'
services:
  postgres:
    image: postgres:13.2
    container_name: ecom-user-server-postgres
    hostname: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - ecom-user-server-network
  keycloak:
    image: jboss/keycloak:latest
    container_name: ecom-user-server-keycloak
    hostname: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - ./volumes/keycloak/imports:/opt/jboss/keycloak/imports
    command:
      - '-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json'
    ports:
      - 8080:8080
    networks:
      - ecom-user-server-network
networks:
  ecom-user-server-network:
    driver: bridge