server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
eureka:
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'false'
    serviceUrl:
      defaultZone: http://${discovery.server.address:localhost}:${discovery.server.port:8761}/eureka/
  instance:
    preferIpAddress: 'true'