server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: production
          url: lb://production
          predicates:
            - Path=/production/**
        - id: image
            url: lb://image
            predicates:
              - Path=/image/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${DISCOVERT_SERVER_ADDRESS:localhost}:${DISCOVERT_SERVER_PORT:8761}/eureka/