spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'