server:
  port: 9020

spring:
  data:
    mongodb:
      host: ${MONGODB_HOSTNAME:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:production}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:password}
      authentication-database: admin
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERT_SERVER_ADDRESS:localhost}:${DISCOVERT_SERVER_PORT:8761}/eureka/

keycloak:
  realm: ecom
  auth-server-url: http://${KEYCLOAK_URL:localhost}:${KEYCLOAK.PORT:8080}/auth
  resource: common-client
  public-client: true

kafka:
  bootstrap-server: localhost:29092
  topics:
    log: log