spring:
  data:
    mongodb:
      host: ${mongodb.hostname:localhost}
      post: ${mongodb.port:27017}
      database: users
      username: ${mongodb.username:root}
      password: ${mongodb.password:password}
      authentication-database: admin
      auto-index-creation: true